import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Switch, Text, useWindowDimensions, View } from "react-native";
import { useRouter } from "expo-router";
import { AppNavigation } from "../components/navigation";
import { AppIcon, Badge, Button, EmptyState, Field, SectionHeading, Surface } from "../components/ui";
import { breakpoints, colors, layout, radius, spacing, typography } from "../constants/theme";
import { useDemoAccount } from "../contexts/account";
import { demoProfessionalProfile, demoProfessionalServices, demoWeekdays } from "../data/mock-professional";

const SECTIONS = ["Vue d’ensemble", "Profil professionnel", "Services", "Disponibilités", "Demandes reçues", "Devis envoyés"] as const;
type Section = typeof SECTIONS[number];

export default function ProfessionalScreen() {
  const router = useRouter();
  const { width } = useWindowDimensions();
  const { account, enableArtisanMode } = useDemoAccount();
  const [section, setSection] = useState<Section>("Vue d’ensemble");
  const [available, setAvailable] = useState(false);
  const [activeDays, setActiveDays] = useState<string[]>(["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi"]);
  const [displayName, setDisplayName] = useState<string>(demoProfessionalProfile.displayName);
  const [description, setDescription] = useState<string>(demoProfessionalProfile.description);
  const isWide = width >= breakpoints.desktop;

  return (
    <View style={styles.root}>
      <AppNavigation activeRoute="/pro" />
      <ScrollView contentContainerStyle={styles.scroll}>
        <View style={[styles.content, isWide && styles.contentWide]}>
          <View style={styles.header}><Text style={styles.eyebrow}>VOTRE COMPTE UNIQUE · ESPACE PROFESSIONNEL</Text><Text style={styles.title}>{section}</Text><Text style={styles.subtitle}>Votre activité artisan reste liée à votre profil personnel.</Text></View>
          {!account.artisanEnabled ? <Surface style={styles.notice}><View style={styles.noticeIcon}><AppIcon name="users" color={colors.primary} /></View><Text style={styles.cardTitle}>Activez votre activité professionnelle</Text><Text style={styles.body}>Une identité, un seul compte. Le mode artisan est uniquement simulé ici et ne publie aucune fiche.</Text><Button label="Activer sur mon compte" onPress={() => { enableArtisanMode(); setSection("Vue d’ensemble"); }} /></Surface> : <>
            <View style={styles.modeSwitch}><View style={styles.modeCopy}><Text style={styles.modeTitle}>Compte unique</Text><Text style={styles.helper}>Espace professionnel actif · pas de second profil</Text></View><Button label="Espace personnel" variant="quiet" compact onPress={() => router.push("/profil")} /></View>
            <Surface style={styles.disclaimer}><Text style={styles.disclaimerText}>Aucune donnée métier n’est connectée. Les réglages ci-dessous restent temporaires et locaux à cette session.</Text></Surface>
            <View style={styles.sectionNav}>{SECTIONS.map((item) => <Pressable key={item} accessibilityRole="tab" accessibilityState={{ selected: section === item }} onPress={() => setSection(item)} style={[styles.navItem, section === item && styles.navItemSelected]}><Text style={[styles.navText, section === item && styles.navTextSelected]}>{item}</Text></Pressable>)}</View>
            {section === "Vue d’ensemble" ? <Overview onSelect={setSection} onOpenRequests={() => router.push("/demandes")} available={available} onAvailabilityChange={setAvailable} /> : null}
            {section === "Profil professionnel" ? <Surface style={styles.panel}><SectionHeading title="Votre fiche publique" /><Text style={styles.body}>Modifications prévisualisées localement. Aucun profil ne sera publié.</Text><Field label="Nom affiché (exemple)" value={displayName} onChangeText={setDisplayName} placeholder="Nom de démonstration" /><Field label="Présentation fictive" value={description} onChangeText={setDescription} multiline /><ProfileValue label="Métier principal" value={demoProfessionalProfile.trade} /><ProfileValue label="Zone d’intervention" value={demoProfessionalProfile.area} /><ProfileValue label="Vérification" value={demoProfessionalProfile.verification} /><Button label="Voir ma fiche publique" variant="secondary" onPress={() => router.push("/artisan/plombier-1")} /></Surface> : null}
            {section === "Services" ? <View style={styles.sectionBody}><SectionHeading title="Mes services" action={<Text style={styles.helper}>Tarifs non configurés</Text>} />{demoProfessionalServices.map((item) => <View key={item.id} style={styles.serviceRow}><View style={styles.serviceIcon}><AppIcon name="check" size={16} color={colors.primary} /></View><Text style={styles.serviceTitle}>{item.title}</Text><Badge label={item.active ? "Actif · démo" : "Inactif · démo"} tone={item.active ? "success" : "neutral"} /></View>)}<Button label="Ajouter un service (exemple)" variant="secondary" onPress={() => undefined} /></View> : null}
            {section === "Disponibilités" ? <Surface style={styles.panel}><SectionHeading title="Disponibilités" /><View style={styles.switchRow}><View style={styles.switchCopy}><Text style={styles.cardTitle}>Disponible maintenant</Text><Text style={styles.helper}>État local de démonstration, non visible publiquement.</Text></View><Switch value={available} onValueChange={setAvailable} accessibilityLabel="Disponibilité de démonstration" trackColor={{ true: colors.primary }} /></View><Text style={styles.sectionLabel}>Jours d’exemple</Text>{demoWeekdays.map((day) => <Pressable key={day} accessibilityRole="checkbox" accessibilityState={{ checked: activeDays.includes(day) }} onPress={() => setActiveDays((current) => current.includes(day) ? current.filter((item) => item !== day) : [...current, day])} style={styles.dayRow}><Text style={styles.body}>{day}</Text><Text style={styles.dayValue}>{activeDays.includes(day) ? "Sélectionné · démo" : "Non sélectionné"}</Text></Pressable>)}<Text style={styles.helper}>Aucune heure ou disponibilité réelle n’est déclarée.</Text></Surface> : null}
            {section === "Demandes reçues" ? <EmptyState title="Aucune demande reçue" description="Les données réelles apparaîtront après raccordement du service. Les exemples clients ne sont pas des demandes reçues." icon="list" action={<Button label="Voir mon espace activité" variant="secondary" onPress={() => router.push("/demandes")} />} /> : null}
            {section === "Devis envoyés" ? <EmptyState title="Aucun devis envoyé" description="La création, l’envoi et le suivi des devis ne sont pas connectés à cette démo." icon="create" action={<Button label="Voir mes devis d’exemple" variant="secondary" onPress={() => router.push("/demandes")} />} /> : null}
          </>}
        </View>
      </ScrollView>
    </View>
  );
}

function ProfileValue({ label, value }: { label: string; value: string }) { return <View style={styles.profileValue}><Text style={styles.helper}>{label}</Text><Text style={styles.body}>{value}</Text></View>; }

function Overview({ onSelect, onOpenRequests, available, onAvailabilityChange }: { onSelect: (section: Section) => void; onOpenRequests: () => void; available: boolean; onAvailabilityChange: (value: boolean) => void }) {
  return <View style={styles.sectionBody}><Surface style={styles.panel}><View style={styles.panelHeader}><View><Text style={styles.cardTitle}>{demoProfessionalProfile.displayName}</Text><Text style={styles.helper}>Fiche non publiée · compte utilisateur unique</Text></View><Badge label="DÉMO" /></View><Button label="Modifier mon profil professionnel" variant="secondary" onPress={() => onSelect("Profil professionnel")} /></Surface><View style={styles.metrics}>{["Demandes reçues", "Demandes en attente", "Devis en cours", "Interventions terminées"].map((item) => <View key={item} style={styles.metric}><Text style={styles.metricLabel}>{item}</Text><Text style={styles.metricValue}>—</Text><Text style={styles.helper}>Non connecté</Text></View>)}</View><Surface style={styles.availability}><View style={styles.switchCopy}><Text style={styles.cardTitle}>Disponibilité</Text><Text style={styles.helper}>{available ? "Disponible · réglage de démo" : "Non renseignée"}</Text></View><Switch value={available} onValueChange={onAvailabilityChange} accessibilityLabel="Disponibilité de démonstration" trackColor={{ true: colors.primary }} /></Surface><SectionHeading title="Accès rapide" /><View style={styles.quickLinks}><Button label="Gérer les services" variant="secondary" onPress={() => onSelect("Services")} /><Button label="Gérer mes horaires" variant="secondary" onPress={() => onSelect("Disponibilités")} /><Button label="Voir mes demandes" variant="quiet" onPress={onOpenRequests} /></View><EmptyState title="Pas encore d’activité connectée" description="Aucun graphique ni indicateur fictif : les données apparaîtront lorsque le service métier existera." icon="list" /></View>;
}

const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.background }, scroll: { flexGrow: 1 }, content: { width: "100%", maxWidth: layout.contentMax, alignSelf: "center", padding: layout.pageGutter, paddingBottom: spacing.x10, gap: spacing.x4 }, contentWide: { paddingHorizontal: layout.pageGutterWide, paddingTop: spacing.x8 },
  header: { gap: spacing.x1 }, eyebrow: { ...typography.caption, color: colors.primary, fontWeight: "700", letterSpacing: 0.7 }, title: { ...typography.h1, color: colors.textPrimary }, subtitle: { ...typography.body, color: colors.textSecondary }, modeSwitch: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: spacing.x3, padding: spacing.x3, borderWidth: 1, borderColor: colors.border, borderRadius: radius.large, backgroundColor: colors.surface }, modeCopy: { flex: 1, gap: spacing.x1 }, modeTitle: { ...typography.label, color: colors.primaryDark },
  notice: { gap: spacing.x3, alignItems: "flex-start", borderRadius: radius.xlarge }, noticeIcon: { width: spacing.x12, height: spacing.x12, alignItems: "center", justifyContent: "center", backgroundColor: colors.primarySoft, borderRadius: radius.large }, cardTitle: { ...typography.title, color: colors.textPrimary }, body: { ...typography.bodySmall, color: colors.textSecondary }, disclaimer: { backgroundColor: colors.infoSoft, borderColor: colors.infoSoft, borderRadius: radius.medium }, disclaimerText: { ...typography.caption, color: colors.textSecondary },
  sectionNav: { flexDirection: "row", flexWrap: "wrap", gap: spacing.x2 }, navItem: { minHeight: 40, justifyContent: "center", paddingHorizontal: spacing.x3, borderRadius: radius.pill, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, navItemSelected: { backgroundColor: colors.primarySoft, borderColor: colors.primary }, navText: { ...typography.caption, color: colors.textSecondary }, navTextSelected: { color: colors.primaryDark, fontWeight: "700" },
  sectionBody: { gap: spacing.x3 }, panel: { borderRadius: radius.large, gap: spacing.x3 }, profileValue: { gap: spacing.x1, paddingVertical: spacing.x2, borderBottomWidth: 1, borderBottomColor: colors.border }, panelHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: spacing.x3 }, metrics: { flexDirection: "row", flexWrap: "wrap", gap: spacing.x2 }, metric: { flexGrow: 1, flexBasis: "45%", gap: spacing.x1, padding: spacing.x3, borderBottomWidth: 1, borderBottomColor: colors.border }, metricLabel: { ...typography.caption, color: colors.textSecondary }, metricValue: { ...typography.h2, color: colors.textPrimary }, helper: { ...typography.caption, color: colors.textSecondary },
  availability: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: spacing.x3, borderRadius: radius.large }, switchRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: spacing.x3, paddingBottom: spacing.x2, borderBottomWidth: 1, borderBottomColor: colors.border }, switchCopy: { flex: 1, gap: spacing.x1 }, sectionLabel: { ...typography.label, color: colors.textPrimary, marginTop: spacing.x2 }, dayRow: { minHeight: spacing.x12, flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: spacing.x2, borderBottomWidth: 1, borderBottomColor: colors.border }, dayValue: { ...typography.caption, color: colors.textSecondary }, serviceRow: { minHeight: spacing.x12, flexDirection: "row", alignItems: "center", gap: spacing.x2, paddingVertical: spacing.x2, borderBottomWidth: 1, borderBottomColor: colors.border }, serviceIcon: { width: spacing.x8, height: spacing.x8, borderRadius: radius.medium, alignItems: "center", justifyContent: "center", backgroundColor: colors.primarySoft }, serviceTitle: { ...typography.body, color: colors.textPrimary, flex: 1 }, quickLinks: { flexDirection: "row", flexWrap: "wrap", gap: spacing.x2 },
});
